In [5]:
# array processing package
l = [[1, 1], [2, 2], [3, 5], [4, 5]] # this is a multi-dimensional array
l

[[1, 1], [2, 2], [3, 5], [4, 5]]

In [6]:
# numpy library
import numpy as np

In [7]:
np_arr = np.array(l)
np_arr

array([[1, 1],
       [2, 2],
       [3, 5],
       [4, 5]])

In [8]:
# comparing array types
type(l), type(np_arr) # 'l' is list; 'np_arr' is numpy

(list, numpy.ndarray)

In [9]:
# merging single- dimensional arrays using np
ls1 = [1, 2, 3, 4]
ls2 = [2, 2, 10, 4]
ls3 = [3, 2, 3, 4]

merged = np.array([ls1, ls2, ls3])
merged

array([[ 1,  2,  3,  4],
       [ 2,  2, 10,  4],
       [ 3,  2,  3,  4]])

In [10]:
# determining row and colomn no.
merged.shape

(3, 4)

In [11]:
# determining specific element of the array
merged[1][2] # merged[x][y]- where [x] is row; [y] is colomn

10

In [12]:
# taking a specific range of the array
merged[0:2, 2:]

array([[ 3,  4],
       [10,  4]])

In [13]:
# taking a range of number
np.arange(10, 20) # this will show all the integer number between 10 to 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.ones((2, 4), dtype=int) # this will create a matrix of only one

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.random.rand(2, 2) # this will create a matrix with random elements

array([[0.73467829, 0.14128048],
       [0.22377311, 0.46209787]])

In [20]:
n = np.arange(10, 20)
n.reshape(2, 5) # this will reshape into specific row - colomn matrix

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])